name: Release Charts

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"

      - name: Add Helm repos
        run: |
          helm repo add mongodb https://mongodb.github.io/helm-charts
          helm repo add edge https://mongodb.github.io/edge-kubernetes-operator

      - name: Publish edge-operator-crds
        uses: mongodb/helm-charts/.github/actions/releaser@2a339bb594fb3d459d4052cd7c753234b095edc3
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_repo_url: https://mongodb.github.io/edge-kubernetes-operator
          target: edge-operator-crds
          #dryrun: ${{ github.ref_name != 'main' }}
          work_dir: ${{ github.workspace }}
          mark_latest: true

      - name: Get latest charts from repo
        run: helm repo update

      - name: Publish edge-operator
        uses: mongodb/helm-charts/.github/actions/releaser@2a339bb594fb3d459d4052cd7c753234b095edc3
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_repo_url: https://mongodb.github.io/edge-kubernetes-operator
          target: edge-operator
          #dryrun: ${{ github.ref_name != 'main' }}
          work_dir: ${{ github.workspace }}
          mark_latest: true
